version: "3.5"

services:
    database:
        build:
            context: "./images/${VANILLA_DOCKER_DATABASE}"
        container_name: "database"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        networks:
            - "vanilla_network"
        ports:
            - "3306:3306"
        volumes:
            - "./logs/${VANILLA_DOCKER_DATABASE}:/var/log/mysql"
            - "./resources/etc/mysql/conf.d/:/etc/mysql/conf.d/"
            - "datastorage:/var/lib/mysql"

    php-fpm:
        depends_on:
            - "database"

volumes:
    datastorage:
        # Created by our setup script.
        external: true
